// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Item { path: string, name: string, is_dir: boolean, is_file: boolean, have_access: boolean, extension: string, }